-- public.Admin Request Status
CREATE TYPE "public"."Admin Request Status" AS ENUM (
  'pending',
  'accept',
  'rejected'
);

-- public.Loan Status
CREATE TYPE "public"."Loan Status" AS ENUM (
  'documents',
  'validation',
  'evaluation',
  'signature',
  'depot',
  'complete'
);

-- public.Perception Status
CREATE TYPE "public"."Perception Status" AS ENUM (
  'New',
  'Negotiation',
  'Notice 7 Days',
  'Notice 72h',
  'Pre Collection',
  'Collection',
  'Loss',
  'Resolved'
);

-- public.Request Stages
CREATE TYPE "public"."Request Stages" AS ENUM (
  'Application',
  'Document',
  'Validation',
  'Evaluation',
  'Signature',
  'Deposit',
  'Express Deposit',
  'Completed',
  'Error'
);

-- public.file_treatment_type
CREATE TYPE "public"."file_treatment_type" AS ENUM (
  'normal',
  'priority'
);

-- public.gender_type
CREATE TYPE "public"."gender_type" AS ENUM (
  'male',
  'female',
  'other',
  'prefer-not-to-say'
);

-- public.income_source_type
CREATE TYPE "public"."income_source_type" AS ENUM (
  'employed',
  'saaq',
  'CSST',
  'pension',
  'invalidity',
  'insurance',
  'rqap'
);

-- public.loan_status_type
CREATE TYPE "public"."loan_status_type" AS ENUM (
  'pending',
  'reviewing documents',
  'validation',
  'evaluation',
  'signature',
  'deposit',
  'complete',
  'rejected'
);

-- public.pay_frequency_type
CREATE TYPE "public"."pay_frequency_type" AS ENUM (
  '1month',
  '2weeks',
  'bimonthly',
  '1week'
);

create table public.customers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  first_name character varying null,
  last_name character varying null,
  phone character varying null,
  email character varying null,
  auth_id text null,
  role text null,
  birth_date date null,
  gender public.gender_type null,
  social_insurance_number text null,
  address_line1 text null,
  address_line2 text null,
  city text null,
  province text null,
  postal_code text null,
  income_source public.income_source_type null,
  bank_institution text null,
  pay_frequency public.pay_frequency_type null,
  next_pay_date date null,
  bank_transit text null,
  bank_account text null,
  monthly_pay_amount text null,
  consumer_proposal boolean null,
  bankruptcy boolean null,
  reference1_name text null,
  reference1_phone text null,
  reference1_relationship text null,
  reference2_name text null,
  reference2_phone text null,
  reference2_relationship text null,
  constraint customers_pkey primary key (id)
) TABLESPACE pg_default;

create table public.loan_requests (
  id serial not null,
  customer_id integer not null,
  request_date timestamp with time zone null default now(),
  birth_date date not null,
  gender public.gender_type not null,
  social_insurance_number text null,
  address_line1 text not null,
  address_line2 text null,
  city text not null,
  province text not null,
  postal_code text not null,
  income_source public.income_source_type not null,
  bank_institution text not null,
  pay_frequency public.pay_frequency_type not null,
  next_pay_date date not null,
  consumer_proposal boolean not null default false,
  bankruptcy boolean not null default false,
  file_treatment_method public.file_treatment_type not null default 'normal'::file_treatment_type,
  terms_accepted boolean not null default false,
  privacy_policy_accepted boolean not null default false,
  marketing_opt_in boolean not null default false,
  status public.loan_status_type not null default 'reviewing documents'::loan_status_type,
  status_updated_at timestamp with time zone null default now(),
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  admin_request_status public."Admin Request Status" null default 'pending'::"Admin Request Status",
  loan_id bigint null,
  request_stage public."Request Stages" not null default 'Application'::"Request Stages",
  bank_account text null,
  monthly_pay_amount text null,
  bank_transit text null,
  constraint loan_requests_pkey primary key (id)
) TABLESPACE pg_default;

create table public.loans (
  id serial not null,
  amount numeric(10, 2) not null,
  duration text not null,
  interest_rate numeric(5, 2) not null,
  description text null,
  is_active boolean null default true,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint loans_pkey primary key (id)
) TABLESPACE pg_default;

create table public.perceptions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  stage public."Perception Status" null,
  loan_id integer null,
  constraint perceptions_pkey primary key (id)
) TABLESPACE pg_default;

create table public.references (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  loan_request_id text null,
  name text null,
  phone text null,
  relationship text null,
  reference_order smallint null
) TABLESPACE pg_default;

INSERT INTO loans (
  id,
  amount,
  duration,
  interest_rate,
  description,
  is_active,
  created_at,
  updated_at
) VALUES
  (1, 400.00, '3 Months', 12.99, 'Small short-term loan', true, '2025-02-27 20:21:25.520288+00', '2025-02-27 20:21:25.520288+00'),
  (2, 600.00, '4 Months', 11.99, 'Medium short-term loan', true, '2025-02-27 20:21:25.520288+00', '2025-02-27 20:21:25.520288+00'),
  (3, 800.00, '5 Months', 10.99, 'Medium-term loan', true, '2025-02-27 20:21:25.520288+00', '2025-02-27 20:21:25.520288+00'),
  (4, 1000.00, '5 Months', 9.99, 'Standard medium-term loan', true, '2025-02-27 20:21:25.520288+00', '2025-02-27 20:21:25.520288+00'),
  (5, 1200.00, '6 Months', 9.49, 'Large medium-term loan', true, '2025-02-27 20:21:25.520288+00', '2025-02-27 20:21:25.520288+00'),
  (6, 1400.00, '6 Months', 8.99, 'Premium medium-term loan', true, '2025-02-27 20:21:25.520288+00', '2025-02-27 20:21:25.520288+00');